name: Deploy Backend

on:
  push:
    branches:
      - master  # Trigger the action on push / merged branch ticket to the 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push backend image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/DevOps/
            docker-compose pull backend
            docker-compose up -d backend
