name: Deploy Backend

on:
  push:
    branches:
      - master # Trigger the action on push / merged branch ticket to the 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete the application.properties file
        run: rm -f ./src/main/resources/application.properties
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Give execute permission
        run: chmod +x ./mvnw 
      
      - name: Build the jar file
        run: ./mvnw clean package -DskipTests

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push backend image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/DevOps
            docker-compose pull backend
            docker-compose up -d backend
