name: Deploy PR Backend

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to deploy'
        required: true
        type: string

concurrency:
  group: pr-queue
  cancel-in-progress: false

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.event.pull_request.head.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Delete the application.properties file
        run: rm ./src/main/resources/application.properties  

      - name: Build the jar file
        run: chmod +x ./mvnw && ./mvnw clean package -DskipTests

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-testing:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push backend image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-testing:latest

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/DevOps/
            docker-compose pull backend-testing
            docker-compose up -d backend-testing
